//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisServiceTests.StatisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisService.IQuestionnaireService")]
    public interface IQuestionnaireService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/GetQuestionnaireResponse")]
        StatisServiceContracts.Questionnaire GetQuestionnaire(string questionnaireName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/StoreQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/StoreQuestionnaireResponse")]
        void StoreQuestionnaire(StatisServiceContracts.Questionnaire questionnaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaireResponse")]
        void DeleteQuestionnaire(string questionnaireName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetUserQuestionnaireList", ReplyAction="http://tempuri.org/IQuestionnaireService/GetUserQuestionnaireListResponse")]
        string[] GetUserQuestionnaireList(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuestionnaireServiceChannel : StatisServiceTests.StatisService.IQuestionnaireService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionnaireServiceClient : System.ServiceModel.ClientBase<StatisServiceTests.StatisService.IQuestionnaireService>, StatisServiceTests.StatisService.IQuestionnaireService {
        
        public QuestionnaireServiceClient() {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StatisServiceContracts.Questionnaire GetQuestionnaire(string questionnaireName) {
            return base.Channel.GetQuestionnaire(questionnaireName);
        }
        
        public void StoreQuestionnaire(StatisServiceContracts.Questionnaire questionnaire) {
            base.Channel.StoreQuestionnaire(questionnaire);
        }
        
        public void DeleteQuestionnaire(string questionnaireName) {
            base.Channel.DeleteQuestionnaire(questionnaireName);
        }
        
        public string[] GetUserQuestionnaireList(string userName) {
            return base.Channel.GetUserQuestionnaireList(userName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisService.IQuestionnaireAdministrativeService")]
    public interface IQuestionnaireAdministrativeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/GetQuestionnaireResponse")]
        StatisServiceContracts.Questionnaire GetQuestionnaire(string questionnaireName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/StoreQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/StoreQuestionnaireResponse")]
        void StoreQuestionnaire(StatisServiceContracts.Questionnaire questionnaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaireResponse")]
        void DeleteQuestionnaire(string questionnaireName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetUserQuestionnaireList", ReplyAction="http://tempuri.org/IQuestionnaireService/GetUserQuestionnaireListResponse")]
        string[] GetUserQuestionnaireList(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuestionnaireAdministrativeServiceChannel : StatisServiceTests.StatisService.IQuestionnaireAdministrativeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionnaireAdministrativeServiceClient : System.ServiceModel.ClientBase<StatisServiceTests.StatisService.IQuestionnaireAdministrativeService>, StatisServiceTests.StatisService.IQuestionnaireAdministrativeService {
        
        public QuestionnaireAdministrativeServiceClient() {
        }
        
        public QuestionnaireAdministrativeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionnaireAdministrativeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireAdministrativeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireAdministrativeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StatisServiceContracts.Questionnaire GetQuestionnaire(string questionnaireName) {
            return base.Channel.GetQuestionnaire(questionnaireName);
        }
        
        public void StoreQuestionnaire(StatisServiceContracts.Questionnaire questionnaire) {
            base.Channel.StoreQuestionnaire(questionnaire);
        }
        
        public void DeleteQuestionnaire(string questionnaireName) {
            base.Channel.DeleteQuestionnaire(questionnaireName);
        }
        
        public string[] GetUserQuestionnaireList(string userName) {
            return base.Channel.GetUserQuestionnaireList(userName);
        }
    }
}
